POST http://localhost:5000/api/carts/b9ce4fbf-dd5a-45aa-8a03-0f7fd5ad9f6a/items
Content-Type: application/json
Accept: application/json

{
  "itemId": "987-6543210",
  "quantity": 1
}

###

GET http://localhost:5000/api/carts/b9ce4fbf-dd5a-45aa-8a03-0f7fd5ad9f6a
Accept: application/json